### ISSUE TITLE
Querying validators at height returns error though no pruning occured

### ISSUE THREAD

**Issue by omritoptix** [dymensionxyz/dymension-rdk#141] opened 2023-03-16 14:34 UTC
steps to reproduce on rollappX:

`rollappd q staking validators --height 11803406`

`Error: rpc error: code = InvalidArgument desc = failed to load state at height 11803406; version mismatch on immutable IAVL tree; version does not exist. Version has either been pruned, or is for a future block height (latest height: 12206715): invalid request`

**Comment by anhductn2001** [comment] 2024-05-14 02:37
We close it because we can't reproduce err

**Closed by anhductn2001** 2024-05-14 02:37 UTC
Labels: bug
